# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/protos/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pp/protos/auth.proto\x12\x04\x61uth\"&\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"C\n\x0cUserResponse\x12\x12\n\nid_usuario\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"G\n\x13VerifyTokenResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x94\x01\n\x0b\x41uthService\x12\x41\n\x0eGetUserByEmail\x12\x1b.auth.GetUserByEmailRequest\x1a\x12.auth.UserResponse\x12\x42\n\x0bVerifyToken\x12\x18.auth.VerifyTokenRequest\x1a\x19.auth.VerifyTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERBYEMAILREQUEST']._serialized_start=31
  _globals['_GETUSERBYEMAILREQUEST']._serialized_end=69
  _globals['_USERRESPONSE']._serialized_start=71
  _globals['_USERRESPONSE']._serialized_end=138
  _globals['_VERIFYTOKENREQUEST']._serialized_start=140
  _globals['_VERIFYTOKENREQUEST']._serialized_end=175
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=177
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=248
  _globals['_AUTHSERVICE']._serialized_start=251
  _globals['_AUTHSERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
